# coremark_waves.do
add wave sim:/testbench/dut/*
add wave  \
sim:/testbench/dut/dp/clk \
sim:/testbench/dut/dp/reset \
sim:/testbench/dut/dp/ResultSrc \
sim:/testbench/dut/dp/MemWrite \
sim:/testbench/dut/dp/Load \
sim:/testbench/dut/dp/ALUSrc \
sim:/testbench/dut/dp/RegWrite \
sim:/testbench/dut/dp/ImmSrc \
sim:/testbench/dut/dp/ALUControl \
sim:/testbench/dut/dp/CSRWrite \
sim:/testbench/dut/dp/Jump \
sim:/testbench/dut/dp/Branch \
sim:/testbench/dut/dp/PC \
sim:/testbench/dut/dp/Instr \
sim:/testbench/dut/dp/ALUResult \
sim:/testbench/dut/dp/WriteData \
sim:/testbench/dut/dp/MemWriteOut \
sim:/testbench/dut/dp/LoadOut \
sim:/testbench/dut/dp/Funct3Out \
sim:/testbench/dut/dp/ReadData \
sim:/testbench/dut/dp/InstrD \
sim:/testbench/dut/dp/PCF \
sim:/testbench/dut/dp/InstrF \
sim:/testbench/dut/dp/PCPlus4F \
sim:/testbench/dut/dp/PCNextF \
sim:/testbench/dut/dp/PCD \
sim:/testbench/dut/dp/PCPlus4D \
sim:/testbench/dut/dp/RD1D \
sim:/testbench/dut/dp/RD2D \
sim:/testbench/dut/dp/ImmExtD \
sim:/testbench/dut/dp/oldCSRReadDataD \
sim:/testbench/dut/dp/CSRSrcDataD \
sim:/testbench/dut/dp/Rs1D \
sim:/testbench/dut/dp/Rs2D \
sim:/testbench/dut/dp/RdD \
sim:/testbench/dut/dp/funct3D \
sim:/testbench/dut/dp/CSRAddrD \
sim:/testbench/dut/dp/RegWriteD \
sim:/testbench/dut/dp/ALUSrcD \
sim:/testbench/dut/dp/MemWriteD \
sim:/testbench/dut/dp/LoadD \
sim:/testbench/dut/dp/CSRWriteD \
sim:/testbench/dut/dp/BranchD \
sim:/testbench/dut/dp/JumpD \
sim:/testbench/dut/dp/ResultSrcD \
sim:/testbench/dut/dp/ImmSrcD \
sim:/testbench/dut/dp/ALUControlD \
sim:/testbench/dut/dp/RD1E \
sim:/testbench/dut/dp/RD2E \
sim:/testbench/dut/dp/PCE \
sim:/testbench/dut/dp/PCPlus4E \
sim:/testbench/dut/dp/ImmExtE \
sim:/testbench/dut/dp/oldCSRReadDataE \
sim:/testbench/dut/dp/CSRSrcDataE \
sim:/testbench/dut/dp/newCSRWriteDataE \
sim:/testbench/dut/dp/SrcAE \
sim:/testbench/dut/dp/SrcBE \
sim:/testbench/dut/dp/SrcBEIntermediate \
sim:/testbench/dut/dp/ALUResultE \
sim:/testbench/dut/dp/WriteDataE \
sim:/testbench/dut/dp/PCTargetE \
sim:/testbench/dut/dp/MulDivResultE \
sim:/testbench/dut/dp/Rs1E \
sim:/testbench/dut/dp/Rs2E \
sim:/testbench/dut/dp/RdE \
sim:/testbench/dut/dp/funct3E \
sim:/testbench/dut/dp/CSRAddrE \
sim:/testbench/dut/dp/ZeroE \
sim:/testbench/dut/dp/NegativeE \
sim:/testbench/dut/dp/OverflowE \
sim:/testbench/dut/dp/CarryE \
sim:/testbench/dut/dp/RegWriteE \
sim:/testbench/dut/dp/ALUSrcE \
sim:/testbench/dut/dp/MemWriteE \
sim:/testbench/dut/dp/LoadE \
sim:/testbench/dut/dp/CSRWriteE \
sim:/testbench/dut/dp/BranchE \
sim:/testbench/dut/dp/JumpE \
sim:/testbench/dut/dp/ResultSrcE \
sim:/testbench/dut/dp/ALUControlE \
sim:/testbench/dut/dp/PCSrcE \
sim:/testbench/dut/dp/ALUResultM \
sim:/testbench/dut/dp/WriteDataM \
sim:/testbench/dut/dp/PCPlus4M \
sim:/testbench/dut/dp/PCTargetM \
sim:/testbench/dut/dp/ImmExtM \
sim:/testbench/dut/dp/MulDivResultM \
sim:/testbench/dut/dp/oldCSRReadDataM \
sim:/testbench/dut/dp/newCSRWriteDataM \
sim:/testbench/dut/dp/ReadDataM \
sim:/testbench/dut/dp/AdjustedReadDataM \
sim:/testbench/dut/dp/RdM \
sim:/testbench/dut/dp/funct3M \
sim:/testbench/dut/dp/CSRAddrM \
sim:/testbench/dut/dp/ResultM \
sim:/testbench/dut/dp/RegWriteM \
sim:/testbench/dut/dp/MemWriteM \
sim:/testbench/dut/dp/LoadM \
sim:/testbench/dut/dp/CSRWriteM \
sim:/testbench/dut/dp/ResultSrcM \
sim:/testbench/dut/dp/ALUControlM \
sim:/testbench/dut/dp/ALUResultW \
sim:/testbench/dut/dp/AdjustedReadDataW \
sim:/testbench/dut/dp/PCPlus4W \
sim:/testbench/dut/dp/PCTargetW \
sim:/testbench/dut/dp/ImmExtW \
sim:/testbench/dut/dp/MulDivResultW \
sim:/testbench/dut/dp/oldCSRReadDataW \
sim:/testbench/dut/dp/newCSRWriteDataW \
sim:/testbench/dut/dp/ResultW \
sim:/testbench/dut/dp/RdW \
sim:/testbench/dut/dp/CSRAddrW \
sim:/testbench/dut/dp/RegWriteW \
sim:/testbench/dut/dp/CSRWriteW \
sim:/testbench/dut/dp/ResultSrcW \
sim:/testbench/dut/dp/ALUControlW \
sim:/testbench/dut/dp/StallF \
sim:/testbench/dut/dp/StallD \
sim:/testbench/dut/dp/FlushD \
sim:/testbench/dut/dp/FlushE \
sim:/testbench/dut/dp/ForwardAE \
sim:/testbench/dut/dp/ForwardBE \
sim:/testbench/dut/dp/entry_addr \
sim:/testbench/dut/dp/IncrementInstret \
sim:/testbench/dut/dp/IncrementAdd \
sim:/testbench/dut/dp/IncrementBranch \
sim:/testbench/dut/dp/IncrementBranchTaken \
sim:/testbench/dut/dp/take_branchE
add wave  \
sim:/testbench/dut/dp/loadUnit/ReadData \
sim:/testbench/dut/dp/loadUnit/ByteAdr \
sim:/testbench/dut/dp/loadUnit/funct3 \
sim:/testbench/dut/dp/loadUnit/AdjustedReadData \
sim:/testbench/dut/dp/loadUnit/byteData \
sim:/testbench/dut/dp/loadUnit/halfwordData

run -all
view wave
